### ISSUE TITLE
[WAS] hikariCP config 1차 조정

### ISSUE THREAD

**Issue by hun-ca** [YAPP-Github/24th-Web-Team-1-BE#89]
- as-is: 기본값
minimum-idle: 10 (기본값)
maximum-pool-size: 10 (기본값)
idle-timeout: 600000 (10분, 기본값)
max-lifetime: 1800000 (30분, 기본값)
connection-timeout: 30000 (30초, 기본값)
validation-timeout: 5000 (5초, 기본값)

```yml
    hikari:
      pool-name: HikariCP
      minimum-idle: 4
      maximum-pool-size: 16
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000  # 30 minutes
      connection-test-query: SELECT 1
```
